[pytest]
testpaths = tests
addopts = -ra
filterwarnings =
    ignore:.*deprecated.*:DeprecationWarning:rdflib\.plugins\.sparql
    ignore:Dataset\.(default_context|contexts) is deprecated.*:DeprecationWarning:rdflib\.
    ignore:ConjunctiveGraph is deprecated.*:DeprecationWarning:rdflib\.plugins\.parsers\.trig
    ignore:'parseAll' argument is deprecated.*:DeprecationWarning:pyparsing\.util
